# Simple Kubernetes Deployment with a simple Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-server
  namespace: default
  labels:
    app: nodejs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-server
  template:
    metadata:
      labels:
        app: nodejs-server
    spec:
      containers:
        - name: nodejs-server
          image: kubeshop/example-api-server:v1.0.0
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-server-svc
  namespace: default
spec:
  selector:
    app: nodejs-server
  ports:
    - port: 3000
      targetPort: 3000
