apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tests
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-controllers
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./tests
  prune: true
  wait: true
  timeout: 5m0s
