---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nodejs-server
  namespace: flux-system
spec:
  interval: 30s
  path: cluster/default/nodejs-server
  prune: true
  sourceRef:
    kind: GitRepository
    name: nodejs-server
  targetNamespace: default

