apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: testkube-helm-release
  namespace: flux-system
spec:
  chart:
    spec:
      chart: testkube
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: testkube
      version: v1.19.11
  interval: 30s
  releaseName: testkube
  targetNamespace: testkube